# Generated by Django 3.1.3 on 2023-06-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='course_id',
        ),
    ]
